### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by vortechron** [bytefury/crater#135]
Got this error "Unable to connect to the DB with Provided Values." while on "Site URL & Database" installation page.

Environtment:
- digital ocean and ubuntu 18.04

**Comment by trapaholics** [comment]
Faced the same error but it was resolved. Check this [link](https://github.com/bytefury/crater/issues/91) out. I also suggest you download the latest zip or clone the latest sources

**Comment by vortechron** [comment]
@trapaholics still not work even by using downloaded zip.

i also already tried giving permission by running this command:
`sudo chgrp -R www-data ./*;sudo chmod -R ug+rwx ./*`

Hm

**Comment by mohitpanjwani** [comment]
@vortechron Please mention the Crater version, Database driver & version as well.. so we can check what's wrong..

**Comment by vortechron** [comment]
@mohitpanjwani latest version, mysql 5.8. till this day i still cannot install crater, various style of installation has been done such as, zip and unzip, and github clone.. Please provide proper installation step for those who are facing this issue. tq

**Comment by mohitpanjwani** [comment]
I think this should no longer be an issue with V4. 

If you still encounter the same issue, please feel free to re-open the issue.

**Comment by 25Kishan** [comment]
![Screenshot from 2021-11-11 13-51-18](https://user-images.githubusercontent.com/41118257/141415683-1bd1072a-3309-44bf-86ae-40ce2a32fbb0.png)
I am getting this error at the time of on-boarding process.
So am I doing anything wrong?
