### ISSUE TITLE
Invalid number passed when save new payment

### ISSUE THREAD

**Issue by diegojbs** [bytefury/crater#362]
**Describe the bug**
I receive a red color toast with message (Invalid number passed.) when i try save new payment.

**Expected behavior**
Server nginx, php 7.4, mysql 5.7.

**Screenshot
https://drive.google.com/file/d/1acoI2D54U0kaKK_ke9TCPynpSRomFm3n/view?usp=sharing

**Please complete the following information:**
- Crater version: 4.0.4
- PHP version: 7.4
- Database type and version: mysql 5.7

**Optional info**
- OS:  Ubuntu server 20.04
- Browser: Chrome

**Comment by mohitpanjwani** [comment]
@diegojbs I've fixed this issue on this commit: https://github.com/bytefury/crater/commit/f47029ca78e74386c56777df3e779d47aede9337

I'll release a minor update shortly for other users but meanwhile you can update the file manually to fix this.

**Comment by nessunollc** [comment]
Regarding closed issue #362.  I'm getting this same issue.   "Invalid number passed" when trying to save a payment.  Updated software to 4.0.4 yesterday feb/27/21 and error persists.
